### ISSUE TITLE
issues about Guide.so

### ISSUE THREAD

**Issue by 993984583** [GongXudong/fly-craft#1]
Could you  tell me what Guide.so does and I'd appreciate it if you'd share the source code of this dynamic library if you'd like!

**Comment by GongXudong** [comment]
"Guide.so" is the dynamic link library of the PID controller we used to generate expert data for the VVC task. This part is not the core contribution of our paper "Goal-Conditioned On-Policy Reinforcement Learning", and we have not plan to open source this code till now. However, we provide an example of how to use "Guide.so" to generate expert data in the README.md:

```python
cd VVC
python runF16/rollout/rollout_guide_parallel.py
```

Besides，we have open-source expert data at OpenML. The 4 expert demonstration datasets are: [$D_E^0$](https://openml.org/search?type=data&status=active&id=46011), [$D_E^1$](https://openml.org/search?type=data&status=active&id=46013), [$D_E^2$](https://openml.org/search?type=data&status=active&id=46015), [$D_E^3$](https://openml.org/search?type=data&status=active&id=46017).

Thank you for your interest in our work. Due to the current code repository mixing the environment and algorithm altogether, it might be challenging to follow. Therefore, we have split it into two separate repositories: one for the environment, [fly-craft](https://github.com/GongXudong/fly-craft), and another for various algorithms applied on fly-craft, [fly-craft-examples](https://github.com/GongXudong/fly-craft-examples). These two repositories are more straightforward, and we recommend to refer to them.

**Comment by GongXudong** [comment]
"Guide.so" is the dynamic link library of the PID controller we used to generate expert data for the VVC task. We have not plan to open source this code till now. However, we provide an example of how to use "Guide.so" to generate expert data in the README.md of [fly-craft-examples](https://github.com/GongXudong/fly-craft-examples):

```python
# sample trajectories single-processing
python demonstrations/rollout_trajs/rollout_by_pid.py --data-dir-suffix v5 --step-frequence 10 --v-min 100 --v-max 110 --v-interval 10 --mu-min -5 --mu-max 5 --mu-interval 5 --chi-min -5 --chi-max 5 --chi-interval 5

# sample trajectories multi-processing with Ray
python demonstrations/rollout_trajs/rollout_by_pid_parallel.py --data-dir-suffix v4 --step-frequence 10 --v-min 100 --v-max 110 --v-interval 10 --mu-min -5 --mu-max 5 --mu-interval 5 --chi-min -5 --chi-max 5 --chi-interval 5

```

Besides，we have open-source expert data at OpenML. The 4 expert demonstration datasets are: [$D_E^0$](https://openml.org/search?type=data&status=active&id=46011), [$D_E^1$](https://openml.org/search?type=data&status=active&id=46013), [$D_E^2$](https://openml.org/search?type=data&status=active&id=46015), [$D_E^3$](https://openml.org/search?type=data&status=active&id=46017).

**Comment by 993984583** [comment]
Thanks for your answer.
